name: Build and deploy myself

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults: 
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install goland
        run: go mod tidy

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Gen templ files
        run: templ generate

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tailwind/package-lock.json

      - name: Tailwind me
        run: |
          cd tailwind
          npm ci
          npm run build-css-prod

      - name: Build static site
        run: go run ./cmd/gen/main.go

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    needs: build
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
