name: Build and deploy myself

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults: 
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install goland
        run: go mod tidy

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Gen templ files
        run: templ generate

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: tailwind/package-lock.json

      - name: Tailwind me
        run: |
          cd tailwind
          npm ci
          npm run build-css-prod

      - name: Build static site
        run: go run ./cmd/gen/main.go

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: static-site
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout `gh-pages` Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download Built Static Site
        uses: actions/download-artifact@v4
        with:
          name: static-site
          path: .

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git commit -m "Deploy static site from tag ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin gh-pages
